site_name: plumed-tools Documentation
theme:
  name: readthedocs
  locale: en

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - API Reference: reference.md

